### ISSUE TITLE
Value area is incorrect

### ISSUE THREAD

**Issue by sampatel012** [bfolkens/py-market-profile#2]
Hi,

The Value area this creates( ie VAL and VAH) is incorrect. I checked with other platforms and it is quite bit off.

Sam

**Comment by bfolkens** [comment]
Thanks Sam - do you have some sample data that you could send over?  I can take a look.  There's a big difference between using Time (TPO) vs. Volume.

**Comment by sampatel012** [comment]
Thanks for looking into it. The exact values are suppose to be as below for this.
PXD : Actual POC:  157.00000000 VAH:  164.222222222 VAL:  150.09000000



    On Monday, May 7, 2018, 2:22:16 PM EDT, Brad Folkens <notifications@github.com> wrote:  
 
 
Thanks Sam - do you have some sample data that you could send over? I can take a look. There's a big difference between using Time (TPO) vs. Volume.

**Comment by bfolkens** [comment]
Thanks @sampatel012 - is there a way you can attach this as a file instead?

**Comment by sampatel012** [comment]
I did attach it as file? you did not get it?
    On Monday, May 7, 2018, 5:03:08 PM EDT, Brad Folkens <notifications@github.com> wrote:  
 
 
Thanks @sampatel012 - is there a way you can attach this as a file instead?
  
[PXD_30.txt](https://github.com/bfolkens/py-market-profile/files/1981483/PXD_30.txt)

**Comment by bfolkens** [comment]
Got it this time, thanks!

Also, where did you get the ground truth / reference numbers from (the POC, VAH, VAL) above?

**Comment by bfolkens** [comment]
Also, what's the format of this file?  In other words, which columns are which? (Timestamp,Close,High,Low,Volume,Open)?

**Comment by sampatel012** [comment]
Sorry for the delayed response.

- Also, where did you get the ground truth / reference numbers from (the POC, VAH, VAL) above?
    ThinkOrSwim
- Also, what's the format of this file? In other words, which columns are which? 
  Date, Open, High, Low, Close, Volume, Adj_Close

**Comment by bfolkens** [comment]
Thanks @sampatel012 - finally getting around to this.  Do you know if ToS was set to TPO (Time-price opportunity) or Volume Profile?

**Comment by bfolkens** [comment]
Also, one more thing, what's the row_size set to?  (If you can provide sample code in a gist that could help me repro).

**Comment by jonatasduval** [comment]
Hello,

I have encountered the same problem with TPO profile calculation, it seems you are using the close value instead of the high/low:

code:
for index, row in df.iterrows():
    x = datetime.strptime(row[0] + " " + row[1], '%d/%m/%Y %H:%M:%S')
    df.loc[index, 'Timestamp'] = x
df = df.drop(columns=["Time", "Date"])
df.set_index('Timestamp', inplace=True, drop=True)
df.head()
mp = market_profile.MarketProfile(df, tick_size=0.5, mode='tpo')
print(mp)
mp_slice = mp[df.index.max() - pd.Timedelta(8.5, 'h'):df.index.max()]

sample data:
Date      ,Time    ,Open  ,High  ,Low   ,Close
27/06/2018,09:00:00,3794  ,3813.5,3791.5,3813
27/06/2018,09:30:00,3813  ,3827  ,3811  ,3822.5
27/06/2018,10:00:00,3822  ,3833  ,3820  ,3831.5
27/06/2018,10:30:00,3831.5,3834.5,3824  ,3832
27/06/2018,11:00:00,3832  ,3843.5,3824.5,3841.5
27/06/2018,11:30:00,3841  ,3843  ,3834  ,3842
27/06/2018,12:00:00,3842.5,3846.5,3838  ,3844.5
27/06/2018,12:30:00,3844  ,3861.5,3844  ,3853.5
27/06/2018,13:00:00,3853  ,3864  ,3848  ,3861.5
27/06/2018,13:30:00,3861.5,3866  ,3852  ,3856.5
27/06/2018,14:00:00,3855.5,3863.5,3851  ,3860
27/06/2018,14:30:00,3860  ,3864  ,3851  ,3853
27/06/2018,15:00:00,3853  ,3858.5,3851  ,3858
27/06/2018,15:30:00,3859  ,3873  ,3858  ,3870.5
27/06/2018,16:00:00,3870.5,3876  ,3867  ,3868.5
27/06/2018,16:30:00,3868  ,3877  ,3868  ,3876
27/06/2018,17:00:00,3876  ,3879  ,3868.5,3868.5
27/06/2018,17:30:00,3869  ,3877.5,3853  ,3861

shuold return:
VAH 3878
POC 3858
VAL 3835 

you can check using this online calculator: https://www.mypivots.com/investment-calculators/market-profile-calculator

**Comment by bfolkens** [comment]
Ahh yes, I’m definitely using Close, on purpose.  Perhaps we could
implement an option to use whichever field the user prefers.


On June 29, 2018 at 4:33:58 PM, jonatasduval (notifications@github.com)
wrote:

Hello,

I have encountered the same problem with TPO profile calculation, it seems
you are using the close value instead of the high/low:

code:
for index, row in df.iterrows():
x = datetime.strptime(row[0] + " " + row[1], '%d/%m/%Y %H:%M:%S')
df.loc[index, 'Timestamp'] = x
df = df.drop(columns=["Time", "Date"])
df.set_index('Timestamp', inplace=True, drop=True)
df.head()
mp = market_profile.MarketProfile(df, tick_size=0.5, mode='tpo')
print(mp)
mp_slice = mp[df.index.max() - pd.Timedelta(8.5, 'h'):df.index.max()]

sample data:
Date ,Time ,Open ,High ,Low ,Close
27/06/2018,09:00:00,3794 ,3813.5,3791.5,3813
27/06/2018,09:30:00,3813 ,3827 ,3811 ,3822.5
27/06/2018,10:00:00,3822 ,3833 ,3820 ,3831.5
27/06/2018,10:30:00,3831.5,3834.5,3824 ,3832
27/06/2018,11:00:00,3832 ,3843.5,3824.5,3841.5
27/06/2018,11:30:00,3841 ,3843 ,3834 ,3842
27/06/2018,12:00:00,3842.5,3846.5,3838 ,3844.5
27/06/2018,12:30:00,3844 ,3861.5,3844 ,3853.5
27/06/2018,13:00:00,3853 ,3864 ,3848 ,3861.5
27/06/2018,13:30:00,3861.5,3866 ,3852 ,3856.5
27/06/2018,14:00:00,3855.5,3863.5,3851 ,3860
27/06/2018,14:30:00,3860 ,3864 ,3851 ,3853
27/06/2018,15:00:00,3853 ,3858.5,3851 ,3858
27/06/2018,15:30:00,3859 ,3873 ,3858 ,3870.5
27/06/2018,16:00:00,3870.5,3876 ,3867 ,3868.5
27/06/2018,16:30:00,3868 ,3877 ,3868 ,3876
27/06/2018,17:00:00,3876 ,3879 ,3868.5,3868.5
27/06/2018,17:30:00,3869 ,3877.5,3853 ,3861

shuold return:
VAH 3878
POC 3858
VAL 3835

you can check using this online calculator:
https://www.mypivots.com/investment-calculators/market-profile-calculator

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/bfolkens/py-market-profile/issues/2#issuecomment-401391025>,
or mute the thread

**Comment by jonatasduval** [comment]
why is the POC/VAH/VAL returned  different from mypivots website or other tools ? is that an error in the calculation or some other kind of TPO profile ?

**Comment by bfolkens** [comment]
It's possible the settings for the buckets (candles), tick size, and other settings are different.  Also if the implementation you're used to is using Low/High values instead of Close, that's certainly reason for difference as well.  We would need to look into the implementation you're referencing to determine.  I placed a reference on this line to show the point of reference for this code:

https://github.com/bfolkens/py-market-profile/blob/1dbed345e56fa2fc328c7e2f8f31497ae56dbfe4/src/market_profile/__init__.py#L90

**Comment by jonatasduval** [comment]
the whole day is not being considered for the tpo count, i have made this modification:

import pylab as pl 
      if self.mp.mode == 'tpo':
            day_range = pl.frange(self.ds["Low"].min(), self.ds["High"].max(), self.mp.tick_size)

            self.profile = pd.Series()
            for value in day_range:
                for index, row in self.ds.iterrows():
                    if value >= row["Low"] and value <= row["High"]:
                        self.profile[value] = self.profile.get(value, 0) + 1

output:
Initial balance: 3791.500000, 3833.000000
Opening range: 3791.500000, 3813.500000
POC: 3858.000000
Profile range: 3791.500000, 3879.000000
Value area: 3835.500000, 3879.000000
Balanced Target: 3924.500000

**Comment by bfolkens** [comment]
Thanks @jonatasduval - can you make a patch and submit a PR with those changes?
