### ISSUE TITLE
Market Profile VS Volume Profile VS Tick Distribution

### ISSUE THREAD

**Issue by ghost** [bfolkens/py-market-profile#4]
I need to point out one thing not clear (at least, to me):
1. On the MarketProfile tool, we can select TPO or VOL, in order to point the calculation on:
- TPO: NUMBER OF HITS of each price on 30 minutes timeframe
- VOL: VOLUME of each price on 30 minutes timeframe

![image](https://user-images.githubusercontent.com/10340922/62448087-36c67100-b767-11e9-8176-668592ff90f8.png)

2. This is working with a OHLCV dataset. What do you expect to happen if the strategy is applied on a TICK data dataset, where each tick is a contract / trade (clearly, the ['close'] pointer will be modified to ['price'])? I would say that the TPO strategy result is modified from Market Profile to Tick Distribution. Is that right?

**Comment by ghost** [comment]
I tried by myself and, changing couple of references about 'High', 'Low', 'Close' and 'Volume', i can drop in NOT aggregated data (like OHLCV) but Tick data:

![image](https://user-images.githubusercontent.com/10340922/62497797-47193300-b7dd-11e9-9f65-9cfdb11dbee3.png)

While using the mode=TPO parameter, the returned profile shows the number of ticks distributed on each specific price threshold.

**Comment by bfolkens** [comment]
Hi @StefanoCore - sorry for the delay.  TPO stands for "Time Price Opportunity," or in other words, the trades bucketed by certain time increments instead of the VOL which is grouped by volume.  Sometimes these terms are commingled, where trades will call a profile chart of TPOs a "Market Profile" and a profile chart based on the volume distribution a "Volume Profile" chart.

Here's an article that tries to explain the difference:
https://jimdaltontrading.com/tpo-vs-volume-profile/
